// File generated from our OpenAPI spec by Stainless.

package com.llama.llamastack.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.llama.llamastack.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ChatCompletionChunkTest {

    @Test
    fun create() {
        val chatCompletionChunk =
            ChatCompletionChunk.builder()
                .id("id")
                .addChoice(
                    ChatCompletionChunk.Choice.builder()
                        .delta(
                            ChatCompletionChunk.Choice.Delta.builder()
                                .content("content")
                                .refusal("refusal")
                                .role("role")
                                .addToolCall(
                                    ChatCompletionChunk.Choice.Delta.ToolCall.builder()
                                        .id("id")
                                        .function(
                                            ChatCompletionChunk.Choice.Delta.ToolCall.Function
                                                .builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .index(0L)
                                        .build()
                                )
                                .build()
                        )
                        .finishReason("finish_reason")
                        .index(0L)
                        .logprobs(
                            ChatCompletionChunk.Choice.Logprobs.builder()
                                .addContent(
                                    ChatCompletionChunk.Choice.Logprobs.Content.builder()
                                        .token("token")
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionChunk.Choice.Logprobs.Content.TopLogprob
                                                .builder()
                                                .token("token")
                                                .logprob(0.0)
                                                .addByte(0L)
                                                .build()
                                        )
                                        .addByte(0L)
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionChunk.Choice.Logprobs.Refusal.builder()
                                        .token("token")
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionChunk.Choice.Logprobs.Refusal.TopLogprob
                                                .builder()
                                                .token("token")
                                                .logprob(0.0)
                                                .addByte(0L)
                                                .build()
                                        )
                                        .addByte(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(0L)
                .model("model")
                .build()

        assertThat(chatCompletionChunk.id()).isEqualTo("id")
        assertThat(chatCompletionChunk.choices())
            .containsExactly(
                ChatCompletionChunk.Choice.builder()
                    .delta(
                        ChatCompletionChunk.Choice.Delta.builder()
                            .content("content")
                            .refusal("refusal")
                            .role("role")
                            .addToolCall(
                                ChatCompletionChunk.Choice.Delta.ToolCall.builder()
                                    .id("id")
                                    .function(
                                        ChatCompletionChunk.Choice.Delta.ToolCall.Function.builder()
                                            .arguments("arguments")
                                            .name("name")
                                            .build()
                                    )
                                    .index(0L)
                                    .build()
                            )
                            .build()
                    )
                    .finishReason("finish_reason")
                    .index(0L)
                    .logprobs(
                        ChatCompletionChunk.Choice.Logprobs.builder()
                            .addContent(
                                ChatCompletionChunk.Choice.Logprobs.Content.builder()
                                    .token("token")
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionChunk.Choice.Logprobs.Content.TopLogprob
                                            .builder()
                                            .token("token")
                                            .logprob(0.0)
                                            .addByte(0L)
                                            .build()
                                    )
                                    .addByte(0L)
                                    .build()
                            )
                            .addRefusal(
                                ChatCompletionChunk.Choice.Logprobs.Refusal.builder()
                                    .token("token")
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionChunk.Choice.Logprobs.Refusal.TopLogprob
                                            .builder()
                                            .token("token")
                                            .logprob(0.0)
                                            .addByte(0L)
                                            .build()
                                    )
                                    .addByte(0L)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(chatCompletionChunk.created()).isEqualTo(0L)
        assertThat(chatCompletionChunk.model()).isEqualTo("model")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val chatCompletionChunk =
            ChatCompletionChunk.builder()
                .id("id")
                .addChoice(
                    ChatCompletionChunk.Choice.builder()
                        .delta(
                            ChatCompletionChunk.Choice.Delta.builder()
                                .content("content")
                                .refusal("refusal")
                                .role("role")
                                .addToolCall(
                                    ChatCompletionChunk.Choice.Delta.ToolCall.builder()
                                        .id("id")
                                        .function(
                                            ChatCompletionChunk.Choice.Delta.ToolCall.Function
                                                .builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .index(0L)
                                        .build()
                                )
                                .build()
                        )
                        .finishReason("finish_reason")
                        .index(0L)
                        .logprobs(
                            ChatCompletionChunk.Choice.Logprobs.builder()
                                .addContent(
                                    ChatCompletionChunk.Choice.Logprobs.Content.builder()
                                        .token("token")
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionChunk.Choice.Logprobs.Content.TopLogprob
                                                .builder()
                                                .token("token")
                                                .logprob(0.0)
                                                .addByte(0L)
                                                .build()
                                        )
                                        .addByte(0L)
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionChunk.Choice.Logprobs.Refusal.builder()
                                        .token("token")
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionChunk.Choice.Logprobs.Refusal.TopLogprob
                                                .builder()
                                                .token("token")
                                                .logprob(0.0)
                                                .addByte(0L)
                                                .build()
                                        )
                                        .addByte(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(0L)
                .model("model")
                .build()

        val roundtrippedChatCompletionChunk =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(chatCompletionChunk),
                jacksonTypeRef<ChatCompletionChunk>(),
            )

        assertThat(roundtrippedChatCompletionChunk).isEqualTo(chatCompletionChunk)
    }
}
