// File generated from our OpenAPI spec by Stainless.

package com.llama.llamastack.models

import com.llama.llamastack.core.JsonValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EvalEvaluateRowsParamsTest {

    @Test
    fun createEvalEvaluateRowsParams() {
        EvalEvaluateRowsParams.builder()
            .inputRows(
                listOf(
                    EvalEvaluateRowsParams.InputRow.builder()
                        .putAdditionalProperty("foo", JsonValue.from(true))
                        .build()
                )
            )
            .scoringFunctions(listOf("string"))
            .taskConfig(
                EvalEvaluateRowsParams.TaskConfig.ofBenchmarkEvalTaskConfig(
                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.builder()
                        .evalCandidate(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.EvalCandidate
                                .ofModelCandidate(
                                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                        .EvalCandidate
                                        .ModelCandidate
                                        .builder()
                                        .model("model")
                                        .samplingParams(
                                            SamplingParams.builder()
                                                .strategy(SamplingParams.Strategy.GREEDY)
                                                .maxTokens(0L)
                                                .repetitionPenalty(0.0)
                                                .temperature(0.0)
                                                .topK(0L)
                                                .topP(0.0)
                                                .build()
                                        )
                                        .type(
                                            EvalEvaluateRowsParams.TaskConfig
                                                .BenchmarkEvalTaskConfig
                                                .EvalCandidate
                                                .ModelCandidate
                                                .Type
                                                .MODEL
                                        )
                                        .systemMessage(
                                            SystemMessage.builder()
                                                .content(InterleavedContent.ofString("string"))
                                                .role(SystemMessage.Role.SYSTEM)
                                                .build()
                                        )
                                        .build()
                                )
                        )
                        .type(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.Type.BENCHMARK
                        )
                        .numExamples(0L)
                        .build()
                )
            )
            .taskId("task_id")
            .xLlamaStackProviderData("X-LlamaStack-ProviderData")
            .build()
    }

    @Test
    fun getBody() {
        val params =
            EvalEvaluateRowsParams.builder()
                .inputRows(
                    listOf(
                        EvalEvaluateRowsParams.InputRow.builder()
                            .putAdditionalProperty("foo", JsonValue.from(true))
                            .build()
                    )
                )
                .scoringFunctions(listOf("string"))
                .taskConfig(
                    EvalEvaluateRowsParams.TaskConfig.ofBenchmarkEvalTaskConfig(
                        EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.builder()
                            .evalCandidate(
                                EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                    .EvalCandidate
                                    .ofModelCandidate(
                                        EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                            .EvalCandidate
                                            .ModelCandidate
                                            .builder()
                                            .model("model")
                                            .samplingParams(
                                                SamplingParams.builder()
                                                    .strategy(SamplingParams.Strategy.GREEDY)
                                                    .maxTokens(0L)
                                                    .repetitionPenalty(0.0)
                                                    .temperature(0.0)
                                                    .topK(0L)
                                                    .topP(0.0)
                                                    .build()
                                            )
                                            .type(
                                                EvalEvaluateRowsParams.TaskConfig
                                                    .BenchmarkEvalTaskConfig
                                                    .EvalCandidate
                                                    .ModelCandidate
                                                    .Type
                                                    .MODEL
                                            )
                                            .systemMessage(
                                                SystemMessage.builder()
                                                    .content(InterleavedContent.ofString("string"))
                                                    .role(SystemMessage.Role.SYSTEM)
                                                    .build()
                                            )
                                            .build()
                                    )
                            )
                            .type(
                                EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.Type
                                    .BENCHMARK
                            )
                            .numExamples(0L)
                            .build()
                    )
                )
                .taskId("task_id")
                .xLlamaStackProviderData("X-LlamaStack-ProviderData")
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.inputRows())
            .isEqualTo(
                listOf(
                    EvalEvaluateRowsParams.InputRow.builder()
                        .putAdditionalProperty("foo", JsonValue.from(true))
                        .build()
                )
            )
        assertThat(body.scoringFunctions()).isEqualTo(listOf("string"))
        assertThat(body.taskConfig())
            .isEqualTo(
                EvalEvaluateRowsParams.TaskConfig.ofBenchmarkEvalTaskConfig(
                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.builder()
                        .evalCandidate(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.EvalCandidate
                                .ofModelCandidate(
                                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                        .EvalCandidate
                                        .ModelCandidate
                                        .builder()
                                        .model("model")
                                        .samplingParams(
                                            SamplingParams.builder()
                                                .strategy(SamplingParams.Strategy.GREEDY)
                                                .maxTokens(0L)
                                                .repetitionPenalty(0.0)
                                                .temperature(0.0)
                                                .topK(0L)
                                                .topP(0.0)
                                                .build()
                                        )
                                        .type(
                                            EvalEvaluateRowsParams.TaskConfig
                                                .BenchmarkEvalTaskConfig
                                                .EvalCandidate
                                                .ModelCandidate
                                                .Type
                                                .MODEL
                                        )
                                        .systemMessage(
                                            SystemMessage.builder()
                                                .content(InterleavedContent.ofString("string"))
                                                .role(SystemMessage.Role.SYSTEM)
                                                .build()
                                        )
                                        .build()
                                )
                        )
                        .type(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.Type.BENCHMARK
                        )
                        .numExamples(0L)
                        .build()
                )
            )
        assertThat(body.taskId()).isEqualTo("task_id")
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            EvalEvaluateRowsParams.builder()
                .inputRows(
                    listOf(
                        EvalEvaluateRowsParams.InputRow.builder()
                            .putAdditionalProperty("foo", JsonValue.from(true))
                            .build()
                    )
                )
                .scoringFunctions(listOf("string"))
                .taskConfig(
                    EvalEvaluateRowsParams.TaskConfig.ofBenchmarkEvalTaskConfig(
                        EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.builder()
                            .evalCandidate(
                                EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                    .EvalCandidate
                                    .ofModelCandidate(
                                        EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                            .EvalCandidate
                                            .ModelCandidate
                                            .builder()
                                            .model("model")
                                            .samplingParams(
                                                SamplingParams.builder()
                                                    .strategy(SamplingParams.Strategy.GREEDY)
                                                    .build()
                                            )
                                            .type(
                                                EvalEvaluateRowsParams.TaskConfig
                                                    .BenchmarkEvalTaskConfig
                                                    .EvalCandidate
                                                    .ModelCandidate
                                                    .Type
                                                    .MODEL
                                            )
                                            .build()
                                    )
                            )
                            .type(
                                EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.Type
                                    .BENCHMARK
                            )
                            .build()
                    )
                )
                .taskId("task_id")
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.inputRows())
            .isEqualTo(
                listOf(
                    EvalEvaluateRowsParams.InputRow.builder()
                        .putAdditionalProperty("foo", JsonValue.from(true))
                        .build()
                )
            )
        assertThat(body.scoringFunctions()).isEqualTo(listOf("string"))
        assertThat(body.taskConfig())
            .isEqualTo(
                EvalEvaluateRowsParams.TaskConfig.ofBenchmarkEvalTaskConfig(
                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.builder()
                        .evalCandidate(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.EvalCandidate
                                .ofModelCandidate(
                                    EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig
                                        .EvalCandidate
                                        .ModelCandidate
                                        .builder()
                                        .model("model")
                                        .samplingParams(
                                            SamplingParams.builder()
                                                .strategy(SamplingParams.Strategy.GREEDY)
                                                .build()
                                        )
                                        .type(
                                            EvalEvaluateRowsParams.TaskConfig
                                                .BenchmarkEvalTaskConfig
                                                .EvalCandidate
                                                .ModelCandidate
                                                .Type
                                                .MODEL
                                        )
                                        .build()
                                )
                        )
                        .type(
                            EvalEvaluateRowsParams.TaskConfig.BenchmarkEvalTaskConfig.Type.BENCHMARK
                        )
                        .build()
                )
            )
        assertThat(body.taskId()).isEqualTo("task_id")
    }
}
