// File generated from our OpenAPI spec by Stainless.

package com.llama_stack_client.api.models

import com.llama_stack_client.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PostTrainingSupervisedFineTuneParamsTest {

    @Test
    fun createPostTrainingSupervisedFineTuneParams() {
        PostTrainingSupervisedFineTuneParams.builder()
            .algorithm(PostTrainingSupervisedFineTuneParams.Algorithm.FULL)
            .algorithmConfig(
                PostTrainingSupervisedFineTuneParams.AlgorithmConfig.ofLoraFinetuningConfig(
                    PostTrainingSupervisedFineTuneParams.AlgorithmConfig.LoraFinetuningConfig
                        .builder()
                        .alpha(123L)
                        .applyLoraToMlp(true)
                        .applyLoraToOutput(true)
                        .loraAttnModules(listOf("string"))
                        .rank(123L)
                        .build()
                )
            )
            .dataset(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
            .hyperparamSearchConfig(
                PostTrainingSupervisedFineTuneParams.HyperparamSearchConfig.builder().build()
            )
            .jobUuid("job_uuid")
            .loggerConfig(PostTrainingSupervisedFineTuneParams.LoggerConfig.builder().build())
            .model("model")
            .optimizerConfig(
                PostTrainingSupervisedFineTuneParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingSupervisedFineTuneParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
            .trainingConfig(
                PostTrainingSupervisedFineTuneParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
            .validationDataset(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            PostTrainingSupervisedFineTuneParams.builder()
                .algorithm(PostTrainingSupervisedFineTuneParams.Algorithm.FULL)
                .algorithmConfig(
                    PostTrainingSupervisedFineTuneParams.AlgorithmConfig.ofLoraFinetuningConfig(
                        PostTrainingSupervisedFineTuneParams.AlgorithmConfig.LoraFinetuningConfig
                            .builder()
                            .alpha(123L)
                            .applyLoraToMlp(true)
                            .applyLoraToOutput(true)
                            .loraAttnModules(listOf("string"))
                            .rank(123L)
                            .build()
                    )
                )
                .dataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .metadata(TrainEvalDataset.Metadata.builder().build())
                        .build()
                )
                .hyperparamSearchConfig(
                    PostTrainingSupervisedFineTuneParams.HyperparamSearchConfig.builder().build()
                )
                .jobUuid("job_uuid")
                .loggerConfig(PostTrainingSupervisedFineTuneParams.LoggerConfig.builder().build())
                .model("model")
                .optimizerConfig(
                    PostTrainingSupervisedFineTuneParams.OptimizerConfig.builder()
                        .lr(42.23)
                        .lrMin(42.23)
                        .optimizerType(
                            PostTrainingSupervisedFineTuneParams.OptimizerConfig.OptimizerType.ADAM
                        )
                        .weightDecay(42.23)
                        .build()
                )
                .trainingConfig(
                    PostTrainingSupervisedFineTuneParams.TrainingConfig.builder()
                        .batchSize(123L)
                        .enableActivationCheckpointing(true)
                        .fsdpCpuOffload(true)
                        .memoryEfficientFsdpWrap(true)
                        .nEpochs(123L)
                        .nIters(123L)
                        .shuffle(true)
                        .build()
                )
                .validationDataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .metadata(TrainEvalDataset.Metadata.builder().build())
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.algorithm()).isEqualTo(PostTrainingSupervisedFineTuneParams.Algorithm.FULL)
        assertThat(body.algorithmConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.AlgorithmConfig.ofLoraFinetuningConfig(
                    PostTrainingSupervisedFineTuneParams.AlgorithmConfig.LoraFinetuningConfig
                        .builder()
                        .alpha(123L)
                        .applyLoraToMlp(true)
                        .applyLoraToOutput(true)
                        .loraAttnModules(listOf("string"))
                        .rank(123L)
                        .build()
                )
            )
        assertThat(body.dataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
        assertThat(body.hyperparamSearchConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.HyperparamSearchConfig.builder().build()
            )
        assertThat(body.jobUuid()).isEqualTo("job_uuid")
        assertThat(body.loggerConfig())
            .isEqualTo(PostTrainingSupervisedFineTuneParams.LoggerConfig.builder().build())
        assertThat(body.model()).isEqualTo("model")
        assertThat(body.optimizerConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingSupervisedFineTuneParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
        assertThat(body.trainingConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
        assertThat(body.validationDataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            PostTrainingSupervisedFineTuneParams.builder()
                .algorithm(PostTrainingSupervisedFineTuneParams.Algorithm.FULL)
                .algorithmConfig(
                    PostTrainingSupervisedFineTuneParams.AlgorithmConfig.ofLoraFinetuningConfig(
                        PostTrainingSupervisedFineTuneParams.AlgorithmConfig.LoraFinetuningConfig
                            .builder()
                            .alpha(123L)
                            .applyLoraToMlp(true)
                            .applyLoraToOutput(true)
                            .loraAttnModules(listOf("string"))
                            .rank(123L)
                            .build()
                    )
                )
                .dataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .build()
                )
                .hyperparamSearchConfig(
                    PostTrainingSupervisedFineTuneParams.HyperparamSearchConfig.builder().build()
                )
                .jobUuid("job_uuid")
                .loggerConfig(PostTrainingSupervisedFineTuneParams.LoggerConfig.builder().build())
                .model("model")
                .optimizerConfig(
                    PostTrainingSupervisedFineTuneParams.OptimizerConfig.builder()
                        .lr(42.23)
                        .lrMin(42.23)
                        .optimizerType(
                            PostTrainingSupervisedFineTuneParams.OptimizerConfig.OptimizerType.ADAM
                        )
                        .weightDecay(42.23)
                        .build()
                )
                .trainingConfig(
                    PostTrainingSupervisedFineTuneParams.TrainingConfig.builder()
                        .batchSize(123L)
                        .enableActivationCheckpointing(true)
                        .fsdpCpuOffload(true)
                        .memoryEfficientFsdpWrap(true)
                        .nEpochs(123L)
                        .nIters(123L)
                        .shuffle(true)
                        .build()
                )
                .validationDataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.algorithm()).isEqualTo(PostTrainingSupervisedFineTuneParams.Algorithm.FULL)
        assertThat(body.algorithmConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.AlgorithmConfig.ofLoraFinetuningConfig(
                    PostTrainingSupervisedFineTuneParams.AlgorithmConfig.LoraFinetuningConfig
                        .builder()
                        .alpha(123L)
                        .applyLoraToMlp(true)
                        .applyLoraToOutput(true)
                        .loraAttnModules(listOf("string"))
                        .rank(123L)
                        .build()
                )
            )
        assertThat(body.dataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .build()
            )
        assertThat(body.hyperparamSearchConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.HyperparamSearchConfig.builder().build()
            )
        assertThat(body.jobUuid()).isEqualTo("job_uuid")
        assertThat(body.loggerConfig())
            .isEqualTo(PostTrainingSupervisedFineTuneParams.LoggerConfig.builder().build())
        assertThat(body.model()).isEqualTo("model")
        assertThat(body.optimizerConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingSupervisedFineTuneParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
        assertThat(body.trainingConfig())
            .isEqualTo(
                PostTrainingSupervisedFineTuneParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
        assertThat(body.validationDataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .build()
            )
    }
}
