// File generated from our OpenAPI spec by Stainless.

package com.llama_stack_client.api.models

import com.llama_stack_client.api.models.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PostTrainingPreferenceOptimizeParamsTest {

    @Test
    fun createPostTrainingPreferenceOptimizeParams() {
        PostTrainingPreferenceOptimizeParams.builder()
            .algorithm(PostTrainingPreferenceOptimizeParams.Algorithm.DPO)
            .algorithmConfig(
                PostTrainingPreferenceOptimizeParams.AlgorithmConfig.builder()
                    .epsilon(42.23)
                    .gamma(42.23)
                    .rewardClip(42.23)
                    .rewardScale(42.23)
                    .build()
            )
            .dataset(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
            .finetunedModel("https://example.com")
            .hyperparamSearchConfig(
                PostTrainingPreferenceOptimizeParams.HyperparamSearchConfig.builder().build()
            )
            .jobUuid("job_uuid")
            .loggerConfig(PostTrainingPreferenceOptimizeParams.LoggerConfig.builder().build())
            .optimizerConfig(
                PostTrainingPreferenceOptimizeParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingPreferenceOptimizeParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
            .trainingConfig(
                PostTrainingPreferenceOptimizeParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
            .validationDataset(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            PostTrainingPreferenceOptimizeParams.builder()
                .algorithm(PostTrainingPreferenceOptimizeParams.Algorithm.DPO)
                .algorithmConfig(
                    PostTrainingPreferenceOptimizeParams.AlgorithmConfig.builder()
                        .epsilon(42.23)
                        .gamma(42.23)
                        .rewardClip(42.23)
                        .rewardScale(42.23)
                        .build()
                )
                .dataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .metadata(TrainEvalDataset.Metadata.builder().build())
                        .build()
                )
                .finetunedModel("https://example.com")
                .hyperparamSearchConfig(
                    PostTrainingPreferenceOptimizeParams.HyperparamSearchConfig.builder().build()
                )
                .jobUuid("job_uuid")
                .loggerConfig(PostTrainingPreferenceOptimizeParams.LoggerConfig.builder().build())
                .optimizerConfig(
                    PostTrainingPreferenceOptimizeParams.OptimizerConfig.builder()
                        .lr(42.23)
                        .lrMin(42.23)
                        .optimizerType(
                            PostTrainingPreferenceOptimizeParams.OptimizerConfig.OptimizerType.ADAM
                        )
                        .weightDecay(42.23)
                        .build()
                )
                .trainingConfig(
                    PostTrainingPreferenceOptimizeParams.TrainingConfig.builder()
                        .batchSize(123L)
                        .enableActivationCheckpointing(true)
                        .fsdpCpuOffload(true)
                        .memoryEfficientFsdpWrap(true)
                        .nEpochs(123L)
                        .nIters(123L)
                        .shuffle(true)
                        .build()
                )
                .validationDataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .metadata(TrainEvalDataset.Metadata.builder().build())
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.algorithm()).isEqualTo(PostTrainingPreferenceOptimizeParams.Algorithm.DPO)
        assertThat(body.algorithmConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.AlgorithmConfig.builder()
                    .epsilon(42.23)
                    .gamma(42.23)
                    .rewardClip(42.23)
                    .rewardScale(42.23)
                    .build()
            )
        assertThat(body.dataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
        assertThat(body.finetunedModel()).isEqualTo("https://example.com")
        assertThat(body.hyperparamSearchConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.HyperparamSearchConfig.builder().build()
            )
        assertThat(body.jobUuid()).isEqualTo("job_uuid")
        assertThat(body.loggerConfig())
            .isEqualTo(PostTrainingPreferenceOptimizeParams.LoggerConfig.builder().build())
        assertThat(body.optimizerConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingPreferenceOptimizeParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
        assertThat(body.trainingConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
        assertThat(body.validationDataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .metadata(TrainEvalDataset.Metadata.builder().build())
                    .build()
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            PostTrainingPreferenceOptimizeParams.builder()
                .algorithm(PostTrainingPreferenceOptimizeParams.Algorithm.DPO)
                .algorithmConfig(
                    PostTrainingPreferenceOptimizeParams.AlgorithmConfig.builder()
                        .epsilon(42.23)
                        .gamma(42.23)
                        .rewardClip(42.23)
                        .rewardScale(42.23)
                        .build()
                )
                .dataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .build()
                )
                .finetunedModel("https://example.com")
                .hyperparamSearchConfig(
                    PostTrainingPreferenceOptimizeParams.HyperparamSearchConfig.builder().build()
                )
                .jobUuid("job_uuid")
                .loggerConfig(PostTrainingPreferenceOptimizeParams.LoggerConfig.builder().build())
                .optimizerConfig(
                    PostTrainingPreferenceOptimizeParams.OptimizerConfig.builder()
                        .lr(42.23)
                        .lrMin(42.23)
                        .optimizerType(
                            PostTrainingPreferenceOptimizeParams.OptimizerConfig.OptimizerType.ADAM
                        )
                        .weightDecay(42.23)
                        .build()
                )
                .trainingConfig(
                    PostTrainingPreferenceOptimizeParams.TrainingConfig.builder()
                        .batchSize(123L)
                        .enableActivationCheckpointing(true)
                        .fsdpCpuOffload(true)
                        .memoryEfficientFsdpWrap(true)
                        .nEpochs(123L)
                        .nIters(123L)
                        .shuffle(true)
                        .build()
                )
                .validationDataset(
                    TrainEvalDataset.builder()
                        .columns(TrainEvalDataset.Columns.builder().build())
                        .contentUrl("https://example.com")
                        .build()
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.algorithm()).isEqualTo(PostTrainingPreferenceOptimizeParams.Algorithm.DPO)
        assertThat(body.algorithmConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.AlgorithmConfig.builder()
                    .epsilon(42.23)
                    .gamma(42.23)
                    .rewardClip(42.23)
                    .rewardScale(42.23)
                    .build()
            )
        assertThat(body.dataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .build()
            )
        assertThat(body.finetunedModel()).isEqualTo("https://example.com")
        assertThat(body.hyperparamSearchConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.HyperparamSearchConfig.builder().build()
            )
        assertThat(body.jobUuid()).isEqualTo("job_uuid")
        assertThat(body.loggerConfig())
            .isEqualTo(PostTrainingPreferenceOptimizeParams.LoggerConfig.builder().build())
        assertThat(body.optimizerConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.OptimizerConfig.builder()
                    .lr(42.23)
                    .lrMin(42.23)
                    .optimizerType(
                        PostTrainingPreferenceOptimizeParams.OptimizerConfig.OptimizerType.ADAM
                    )
                    .weightDecay(42.23)
                    .build()
            )
        assertThat(body.trainingConfig())
            .isEqualTo(
                PostTrainingPreferenceOptimizeParams.TrainingConfig.builder()
                    .batchSize(123L)
                    .enableActivationCheckpointing(true)
                    .fsdpCpuOffload(true)
                    .memoryEfficientFsdpWrap(true)
                    .nEpochs(123L)
                    .nIters(123L)
                    .shuffle(true)
                    .build()
            )
        assertThat(body.validationDataset())
            .isEqualTo(
                TrainEvalDataset.builder()
                    .columns(TrainEvalDataset.Columns.builder().build())
                    .contentUrl("https://example.com")
                    .build()
            )
    }
}
